version: '2'
services:

  api:
    container_name: as_api
    build: ./src/AliseeksApi
    ports:
      - "1460:1460"
    links:
      - postgres
      - redis

  postgres:
    container_name: as_postgres
    build: ./postgres

  redis:
    container_name: as_redis
    build: ./redis
