version: '2'
services:

  api:
    env_file:
       - vars.env
    container_name: as_api
    build: ./src/AliseeksApi/bin/Release/netcoreapp1.0/publish
    ports:
      - "${ALISEEKSAPI_PORTMAP}:${ALISEEKSAPI_PORT}"
    external_links:
      - as_postgres
    links:
      - redis

#  postgres:
#    container_name: as_postgres
#    build: ./services/postgres
#    ports:
#       - "5432:5432"
#    environment:
#       - POSTGRES_PASSWORD
#    volumes:
#       - /var/lib/aliseeks/postgres/data:/var/lib/postgresql/data
#    env_file:
#       - vars.env

  redis:
    container_name: as_redis
    build: ./services/redis
    ports:
       - "6379:6379"
    env_file:
       - vars.env
