version: '2'
services:

  postgres:
    container_name: as_postgres
    build: ./postgres
    ports:
       - "5432:5432"
    environment:
       - ALISEEKS_POSTGRES_PASSWORD
    volumes:
       - /var/lib/aliseeks/postgres/data:/var/lib/postgresql/data

  redis:
    container_name: as_redis
    build: ./redis
